Repository TwoDotFive/server, pull requests merged in 2024-09, with the labels that each got.

#25 팬풀 로그 CRUD API 구현
  src/main/java/com/example/temp/baseball/domain/StadiumRepository.java
  src/main/java/com/example/temp/tour/controller/TourController.java
  src/main/java/com/example/temp/tour/domain/TourLog.java
  src/main/java/com/example/temp/tour/domain/TourLogRepository.java
  src/main/java/com/example/temp/tour/domain/TourLogTitle.java
  src/main/java/com/example/temp/tour/domain/TourPlace.java
  src/main/java/com/example/temp/tour/domain/TourPlaceRepository.java
  src/main/java/com/example/temp/tour/domain/TourSchedule.java
  src/main/java/com/example/temp/tour/domain/TourScheduleMemo.java
  src/main/java/com/example/temp/tour/domain/TourScheduleMemoContent.java
  src/main/java/com/example/temp/tour/domain/TourScheduleMemoImage.java
  src/main/java/com/example/temp/tour/domain/TourScheduleMemoImageRepository.java
  src/main/java/com/example/temp/tour/domain/TourScheduleMemoRepository.java
  src/main/java/com/example/temp/tour/domain/TourScheduleRepository.java
  src/main/java/com/example/temp/tour/dto/FindTourInformationResponse.java
  src/main/java/com/example/temp/tour/dto/RegisterTourLogRequest.java
  src/main/java/com/example/temp/tour/dto/TourLogUserProfileView.java
  src/main/java/com/example/temp/tour/dto/TourLogView.java
  src/main/java/com/example/temp/tour/dto/TourPlaceInfo.java
  src/main/java/com/example/temp/tour/dto/TourPlaceView.java
  src/main/java/com/example/temp/tour/dto/TourScheduleDto.java
  src/main/java/com/example/temp/tour/dto/TourScheduleMemoDto.java
  src/main/java/com/example/temp/tour/dto/TourScheduleMemoImageDto.java
  src/main/java/com/example/temp/tour/dto/TourScheduleMemoImageView.java
  src/main/java/com/example/temp/tour/dto/TourScheduleMemoView.java
  src/main/java/com/example/temp/tour/dto/TourScheduleView.java
  src/main/java/com/example/temp/tour/dto/UpdateTourLogRequest.java
  src/main/java/com/example/temp/tour/service/DeleteTourLogService.java
  src/main/java/com/example/temp/tour/service/FindTourLogService.java
  src/main/java/com/example/temp/tour/service/RegisterTourLogService.java
  src/main/java/com/example/temp/tour/service/UpdateTourLogService.java
  src/main/java/com/example/temp/tour/service/impl/DeleteTourLogServiceImpl.java
  src/main/java/com/example/temp/tour/service/impl/FindTourLogServiceImpl.java
  src/main/java/com/example/temp/tour/service/impl/RegisterTourLogServiceImpl.java
  src/main/java/com/example/temp/tour/service/impl/UpdateTourLogServiceImpl.java
Labels: 기능 구현, 리팩토링

#37 투어 로그 최신순 조회 API 구현
  src/main/java/com/example/temp/baseball/domain/StadiumRepository.java
  src/main/java/com/example/temp/tour/controller/TourController.java
  src/main/java/com/example/temp/tour/domain/TourLogRepository.java
  src/main/java/com/example/temp/tour/dto/FindRecentTourLogListResponse.java
  src/main/java/com/example/temp/tour/dto/TourLogPreview.java
  src/main/java/com/example/temp/tour/dto/TourLogPreviewNativeDto.java
  src/main/java/com/example/temp/tour/dto/UserProfileView.java
  src/main/java/com/example/temp/tour/service/FindRecentTourLogListByStadiumService.java
  src/main/java/com/example/temp/tour/service/FindRecentTourLogListService.java
  src/main/java/com/example/temp/tour/service/impl/FindRecentTourLogListByStadiumServiceImpl.java
  src/main/java/com/example/temp/tour/service/impl/FindRecentTourLogListServiceImpl.java
Labels: 기능 구현

#36 #30 사용자 차단, 신고
  src/main/java/com/example/temp/common/entity/ReportedUser.java
  src/main/java/com/example/temp/common/entity/ReportedUserRepository.java
  src/main/java/com/example/temp/user/controller/UserController.java
  src/main/java/com/example/temp/user/domain/BlockedUser.java
  src/main/java/com/example/temp/user/domain/BlockedUserRepository.java
  src/main/java/com/example/temp/user/dto/BlockUserCommand.java
  src/main/java/com/example/temp/user/dto/BlockUserRequest.java
  src/main/java/com/example/temp/user/dto/CheckUserIsBlockedCommand.java
  src/main/java/com/example/temp/user/dto/DeleteUserBlockingCommand.java
  src/main/java/com/example/temp/user/dto/FindUserProfileCommand.java
  src/main/java/com/example/temp/user/dto/ReportUserCommand.java
  src/main/java/com/example/temp/user/dto/ReportUserRequest.java
  src/main/java/com/example/temp/user/service/BlockUserService.java
  src/main/java/com/example/temp/user/service/CheckUserIsBlockedService.java
  src/main/java/com/example/temp/user/service/DeleteUserBlockingService.java
  src/main/java/com/example/temp/user/service/FindUserProfileService.java
  src/main/java/com/example/temp/user/service/ReportUserService.java
  src/main/java/com/example/temp/user/service/impl/BlockUserServiceImpl.java
  src/main/java/com/example/temp/user/service/impl/CheckUserIsBlockedServiceImpl.java
  src/main/java/com/example/temp/user/service/impl/DeleteUserBlockingServiceImpl.java
  src/main/java/com/example/temp/user/service/impl/FindUserProfileServiceImpl.java
  src/main/java/com/example/temp/user/service/impl/ReportUserServiceImpl.java
Labels: 기능 구현

#38 [팬풀 로그] 북마크 기능 구현
  src/main/java/com/example/temp/tour/controller/TourController.java
  src/main/java/com/example/temp/tour/domain/TourLogBookmark.java
  src/main/java/com/example/temp/tour/domain/TourLogBookmarkRepository.java
  src/main/java/com/example/temp/tour/domain/TourLogRepository.java
  src/main/java/com/example/temp/tour/dto/BookmarkedTourLogPreview.java
  src/main/java/com/example/temp/tour/dto/BookmarkedTourLogPreviewNativeDto.java
  src/main/java/com/example/temp/tour/dto/FindUserBookmarkedTourLogListResponse.java
  src/main/java/com/example/temp/tour/dto/RegisterTourLogBookmarkRequest.java
  src/main/java/com/example/temp/tour/service/DeleteTourLogBookmarkService.java
  src/main/java/com/example/temp/tour/service/FindTourLogBookmarkIdService.java
  src/main/java/com/example/temp/tour/service/FindUserBookmarkedTourLogListService.java
  src/main/java/com/example/temp/tour/service/RegisterTourLogBookmarkService.java
  src/main/java/com/example/temp/tour/service/impl/DeleteTourLogBookmarkServiceImpl.java
  src/main/java/com/example/temp/tour/service/impl/FindTourLogBookmarkIdServiceImpl.java
  src/main/java/com/example/temp/tour/service/impl/FindUserBookmarkedTourLogListServiceImpl.java
  src/main/java/com/example/temp/tour/service/impl/RegisterTourLogBookmarkServiceImpl.java
Labels: 기능 구현

#39 #28 API 연동해 관광지 상세 정보 조회 기능
  src/main/java/com/example/temp/tour/controller/TourController.java
  src/main/java/com/example/temp/tour/domain/TourDetails.java
  src/main/java/com/example/temp/tour/dto/FindAccommodationsDetailsResponse.java
  src/main/java/com/example/temp/tour/dto/FindCourseDetailsResponse.java
  src/main/java/com/example/temp/tour/dto/FindCultureDetailsResponse.java
  src/main/java/com/example/temp/tour/dto/FindLeisureSportsDetailsResponse.java
  src/main/java/com/example/temp/tour/dto/FindRestaurantDetailsResponse.java
  src/main/java/com/example/temp/tour/dto/FindShoppingDetailsResponse.java
  src/main/java/com/example/temp/tour/dto/FindSpotDetailsResponse.java
  src/main/java/com/example/temp/tour/dto/FindTourInformationDetailsCommand.java
  src/main/java/com/example/temp/tour/dto/FindTourInformationDetailsResponse.java
  src/main/java/com/example/temp/tour/service/FindTourInformationDetailsService.java
  src/main/java/com/example/temp/tour/service/impl/FindAccommodationDetailsServiceImpl.java
  src/main/java/com/example/temp/tour/service/impl/FindCultureDetailsServiceImpl.java
  src/main/java/com/example/temp/tour/service/impl/FindRestaurantDetailsServiceImpl.java
  src/main/java/com/example/temp/tour/service/impl/FindShoppingDetailsServiceImpl.java
  src/main/java/com/example/temp/tour/service/impl/FindSpotDetailsServiceImpl.java
  src/main/java/com/example/temp/tour/service/impl/FindTourDetailsServiceFactory.java
  src/main/java/com/example/temp/tour/service/impl/FindTourDetailsServiceImpl.java
  src/main/java/com/example/temp/tour/service/impl/TourDetailsClients.java
Labels: 기능 구현

#41 S3 Presigned URL 요청 API 구현
  build.gradle
  src/main/java/com/example/temp/common/config/AwsConfig.java
  src/main/java/com/example/temp/common/config/SecurityConfig.java
  src/main/java/com/example/temp/common/file/FileController.java
  src/main/java/com/example/temp/common/file/FileService.java
Labels: 기능 구현, 인프라

#46 경기장 목록 조회 API - ID 속성 추가
  src/main/java/com/example/temp/baseball/dto/StadiumView.java
Labels: 기능 구현

#47 국문 관광 정보 Request Parameter 관련 수정 사항
  src/main/java/com/example/temp/tour/controller/TourController.java
  src/main/java/com/example/temp/user/dto/UserProfileView.java
Labels: 버그 해결

#48 Presigned-URL 요청 API 엔드포인트 오탈자 정정
  src/main/java/com/example/temp/common/file/FileController.java
Labels: 기타

#51 회원 본인 프로필 조회 기능 추가
  src/main/java/com/example/temp/user/controller/UserController.java
Labels: 기능 구현

#53 [투어 로그] 조회 API 응답에 작성자 식별자 항목 추가
  src/main/java/com/example/temp/tour/dto/TourLogUserProfileView.java
Labels: 기능 구현

#54 chore: AWS SDK 의존성 변경
  build.gradle
Labels: 기타

#55 [팬풀 로그] 팬풀 로그 전용 경기장 엔티티 및 경기장 목록 조회 API 추가
  src/main/java/com/example/temp/tour/controller/TourController.java
  src/main/java/com/example/temp/tour/controller/dto/TourLogStadiumView.java
  src/main/java/com/example/temp/tour/domain/TourLog.java
  src/main/java/com/example/temp/tour/domain/TourLogBookmarkRepository.java
  src/main/java/com/example/temp/tour/domain/TourLogRepository.java
  src/main/java/com/example/temp/tour/domain/TourLogStadium.java
  src/main/java/com/example/temp/tour/domain/TourLogStadiumRepository.java
  src/main/java/com/example/temp/tour/dto/FindAllTourLogStadiumResponse.java
  src/main/java/com/example/temp/tour/service/FindAllTourLogStadiumService.java
  src/main/java/com/example/temp/tour/service/impl/FindAllTourLogStadiumServiceImpl.java
  src/main/java/com/example/temp/tour/service/impl/FindRecentTourLogListByStadiumServiceImpl.java
  src/main/java/com/example/temp/tour/service/impl/RegisterTourLogServiceImpl.java
Labels: 기능 구현, 리팩토링

#56 [팬풀 로그] 등록된 일정 혹은 메모가 없는 경우 팬풀 로그 조회에 실패하는 오류 해결
  src/main/java/com/example/temp/tour/domain/TourLogRepository.java
  src/main/java/com/example/temp/tour/dto/TourScheduleView.java
Labels: 버그 해결

#57 식별자 응답 타입 변경
  src/main/java/com/example/temp/common/dto/IdResponse.java
  src/main/java/com/example/temp/tour/controller/TourController.java
Labels: 리팩토링

#64 링크 공유를 위해 비회원도 투어로그 조회가 가능하도록 인가 변경
  src/main/java/com/example/temp/common/config/SecurityConfig.java
Labels: 기능 변경

#66 특정 관광 장소를 방문하는 팬풀로그 목록 조회 API 구현
  src/main/java/com/example/temp/tour/controller/TourController.java
  src/main/java/com/example/temp/tour/domain/TourLogRepository.java
  src/main/java/com/example/temp/tour/dto/FindRecentTourLogListResponse.java
  src/main/java/com/example/temp/tour/dto/FindTourLogListResponse.java
  src/main/java/com/example/temp/tour/service/FindTourLogListByTourPlaceService.java
  src/main/java/com/example/temp/tour/service/impl/FindTourLogListByTourPlaceServiceImpl.java
Labels: 기능 추가

#65 야구 경기 수정사항 추가 구현
  src/main/java/com/example/temp/baseball/controller/BaseballGameController.java
  src/main/java/com/example/temp/baseball/domain/GameRepository.java
  src/main/java/com/example/temp/baseball/service/CountFanpoolRelatedFanpoolService.java
  src/main/java/com/example/temp/baseball/service/impl/CountFanpoolRelatedFanpoolServiceImpl.java
  src/main/java/com/example/temp/baseball/service/impl/FindAllSchedulesDuringThisWeekServiceImpl.java
  src/main/java/com/example/temp/baseball/service/impl/FindGamesByTeamServiceImpl.java
  src/main/java/com/example/temp/fanpool/domain/FanpoolRepository.java
Labels: 기능 추가, 버그 해결

#67 회원이 등록한 팬풀로그 목록 조회 API 구현
  src/main/java/com/example/temp/tour/controller/TourController.java
  src/main/java/com/example/temp/tour/domain/TourLogRepository.java
  src/main/java/com/example/temp/tour/service/FindTourLogListByUserService.java
  src/main/java/com/example/temp/tour/service/impl/FindTourLogListByUserServiceImpl.java
Labels: 기능 추가

#68 팬풀로그 목록 조회 응답 속성 추가 - 장소 미리보기
  src/main/java/com/example/temp/tour/domain/TourLogBookmarkRepository.java
  src/main/java/com/example/temp/tour/domain/TourLogRepository.java
  src/main/java/com/example/temp/tour/domain/TourSchedule.java
  src/main/java/com/example/temp/tour/dto/BookmarkedTourLogPreview.java
  src/main/java/com/example/temp/tour/dto/BookmarkedTourLogPreviewNativeDto.java
  src/main/java/com/example/temp/tour/dto/TourLogPreview.java
  src/main/java/com/example/temp/tour/dto/TourLogPreviewNativeDto.java
Labels: 기능 추가

#69 JPA 영속성 관련 문제
  src/main/java/com/example/temp/baseball/controller/BaseballGameController.java
  src/main/java/com/example/temp/baseball/dto/UpdatedUserProfileCommand.java
  src/main/java/com/example/temp/baseball/service/impl/FindAllSchedulesDuringThisWeekServiceImpl.java
  src/main/java/com/example/temp/baseball/service/impl/FindAllTeamsInSeasonServiceImpl.java
  src/main/java/com/example/temp/fanpool/controller/FanpoolController.java
  src/main/java/com/example/temp/fanpool/service/impl/FindFanpoolByIdServiceImpl.java
  src/main/java/com/example/temp/fanpool/service/impl/FindFilteredFanpoolServiceImpl.java
  src/main/java/com/example/temp/fanpool/service/impl/FindLatestFanpoolServiceImpl.java
Labels: 버그 해결

#72 첫 회원가입 시 응답코드를 204로 설정하여 ResponseBody가 전달되지 않는 오류 정정
  src/main/java/com/example/temp/user/controller/OAuthController.java
Labels: 버그 해결

#70 인증된 동네 삭제 기능
  src/main/java/com/example/temp/user/controller/UserController.java
  src/main/java/com/example/temp/user/domain/UserAuthenticatedLocationRepository.java
  src/main/java/com/example/temp/user/service/location/DeleteUserAuthenticatedLocationService.java
  src/main/java/com/example/temp/user/service/location/impl/DeleteUserAuthenticatedLocationServiceImpl.java
Labels: 기능 추가

#73 이미 차단된 유저는 Blocked_User에 저장되지 않게 수정 외 수정사항들
  src/main/java/com/example/temp/baseball/controller/BaseballGameController.java
  src/main/java/com/example/temp/baseball/domain/GameRepository.java
  src/main/java/com/example/temp/baseball/domain/TeamRepository.java
  src/main/java/com/example/temp/baseball/service/impl/FindGamesByTeamServiceImpl.java
  src/main/java/com/example/temp/fanpool/controller/FanpoolController.java
  src/main/java/com/example/temp/fanpool/service/impl/FindFilteredFanpoolServiceImpl.java
  src/main/java/com/example/temp/user/controller/UserController.java
  src/main/java/com/example/temp/user/service/impl/BlockUserServiceImpl.java
  src/main/java/com/example/temp/user/service/impl/SaveUserAuthenticatedLocationServiceImpl.java
  src/main/java/com/example/temp/user/service/impl/UpdateUserProfileServiceImpl.java
Labels: 버그 해결

#44 #40 휴대폰번호 인증
  build.gradle
  src/main/java/com/example/temp/common/config/RedisConfig.java
  src/main/java/com/example/temp/common/util/SendSMSService.java
  src/main/java/com/example/temp/user/controller/OAuthController.java
  src/main/java/com/example/temp/user/dto/SendCertificationCodeRequest.java
  src/main/java/com/example/temp/user/dto/VerifyCertificationCodeRequest.java
  src/main/java/com/example/temp/user/service/SendCertificationCodeService.java
  src/main/java/com/example/temp/user/service/VerifyCertificationCodeService.java
  src/main/java/com/example/temp/user/service/impl/SendCertificationCodeServiceImpl.java
  src/main/java/com/example/temp/user/service/impl/VerifyCertificationCodeServiceImpl.java
Labels: 기능 추가
