Repository TwoDotFive/server, pull requests merged in 2024-10, with the labels that each got.

#77 응원팀 설정 안 할 때 NPE 터지는 것 Optional로 수정
  src/main/java/com/example/temp/user/dto/UserProfileView.java
Labels: 버그 해결

#79 채팅 기능 구현
  src/main/java/com/example/temp/chat/config/StompHandler.java
  src/main/java/com/example/temp/chat/config/StompProperties.java
  src/main/java/com/example/temp/chat/config/WebSocketConfig.java
  src/main/java/com/example/temp/chat/controller/ChatController.java
  src/main/java/com/example/temp/chat/controller/ChatRoomController.java
  src/main/java/com/example/temp/chat/controller/StompController.java
  src/main/java/com/example/temp/chat/domain/ChatMessage.java
  src/main/java/com/example/temp/chat/domain/ChatMessagePreview.java
  src/main/java/com/example/temp/chat/domain/ChatMessageRepository.java
  src/main/java/com/example/temp/chat/domain/ChatMessageType.java
  src/main/java/com/example/temp/chat/domain/ChatRoom.java
  src/main/java/com/example/temp/chat/domain/ChatRoomRepository.java
  src/main/java/com/example/temp/chat/domain/ChatRoomUserRepository.java
  src/main/java/com/example/temp/chat/domain/Chatroom.java
  src/main/java/com/example/temp/chat/domain/ChatroomRepository.java
  src/main/java/com/example/temp/chat/domain/ChatroomUser.java
  src/main/java/com/example/temp/chat/domain/ChatroomUserRepository.java
  src/main/java/com/example/temp/chat/domain/UserChatRoom.java
  src/main/java/com/example/temp/chat/domain/UserChatRoomRepository.java
  src/main/java/com/example/temp/chat/dto/ChatMessageDto.java
  src/main/java/com/example/temp/chat/dto/ChatMessageView.java
  src/main/java/com/example/temp/chat/dto/ChatRoomView.java
  src/main/java/com/example/temp/chat/dto/ChatUserProfileView.java
  src/main/java/com/example/temp/chat/dto/CreateChatRoomCommand.java
  src/main/java/com/example/temp/chat/dto/CreateChatRoomRequest.java
  src/main/java/com/example/temp/chat/dto/CreateChatRoomResponse.java
  src/main/java/com/example/temp/chat/dto/CreateChatroomCommand.java
  src/main/java/com/example/temp/chat/dto/CreateChatroomRequest.java
  src/main/java/com/example/temp/chat/dto/FindChatRoomMessagesCommand.java
  src/main/java/com/example/temp/chat/dto/FindChatRoomMessagesResponse.java
  src/main/java/com/example/temp/chat/dto/FindChatroomListNativeDto.java
  src/main/java/com/example/temp/chat/dto/FindChatroomListResult.java
  src/main/java/com/example/temp/chat/dto/FindUserJoinedChatRoomsResponse.java
  src/main/java/com/example/temp/chat/dto/LastMessageView.java
  src/main/java/com/example/temp/chat/dto/SaveChatMessageCommand.java
  src/main/java/com/example/temp/chat/dto/SendChatMessageRequest.java
  src/main/java/com/example/temp/chat/dto/StompChatMessage.java
  src/main/java/com/example/temp/chat/dto/UserProfileView.java
  src/main/java/com/example/temp/chat/service/CreateChatRoomService.java
  src/main/java/com/example/temp/chat/service/CreateChatroomService.java
  src/main/java/com/example/temp/chat/service/ExitChatroomService.java
  src/main/java/com/example/temp/chat/service/FindChatRoomMessagesService.java
  src/main/java/com/example/temp/chat/service/FindChatroomListService.java
  src/main/java/com/example/temp/chat/service/FindChatroomListServiceImpl.java
  src/main/java/com/example/temp/chat/service/FindChatroomMessagesService.java
  src/main/java/com/example/temp/chat/service/FindUserJoinedChatRoomListService.java
  src/main/java/com/example/temp/chat/service/SaveChatMessageService.java
  src/main/java/com/example/temp/chat/service/SendChatMessageService.java
  src/main/java/com/example/temp/chat/service/UpdateUserChatRoomExitTimeService.java
  src/main/java/com/example/temp/chat/service/impl/CreateChatRoomServiceImpl.java
  src/main/java/com/example/temp/chat/service/impl/CreateChatroomServiceImpl.java
  src/main/java/com/example/temp/chat/service/impl/ExitChatroomServiceImpl.java
  src/main/java/com/example/temp/chat/service/impl/FindChatRoomMessagesServiceImpl.java
  src/main/java/com/example/temp/chat/service/impl/FindChatroomMessagesServiceImpl.java
  src/main/java/com/example/temp/chat/service/impl/FindUserJoinedChatRoomListServiceImpl.java
  src/main/java/com/example/temp/chat/service/impl/LeaveChatRoomServiceImpl.java
  src/main/java/com/example/temp/chat/service/impl/SaveChatMessageServiceImpl.java
  src/main/java/com/example/temp/chat/service/impl/SendChatMessageServiceImpl.java
  src/main/java/com/example/temp/chat/service/impl/UpdateUserChatRoomExitTimeServiceImpl.java
  src/main/java/com/example/temp/fanpool/domain/FanpoolRepository.java
Labels: 기능 추가

#80 팬풀 삭제 기능
  src/main/java/com/example/temp/chat/domain/ChatroomUserRepository.java
  src/main/java/com/example/temp/fanpool/controller/FanpoolController.java
  src/main/java/com/example/temp/fanpool/domain/FanpoolRepository.java
  src/main/java/com/example/temp/fanpool/domain/FanpoolUser.java
  src/main/java/com/example/temp/fanpool/domain/FanpoolUserRepository.java
  src/main/java/com/example/temp/fanpool/service/DeleteFanpoolByIdService.java
  src/main/java/com/example/temp/fanpool/service/impl/DeleteFanpoolByIdServiceImpl.java
  src/main/java/com/example/temp/fanpool/service/impl/DeleteFanpoolParticipationServiceImpl.java
  src/main/java/com/example/temp/fanpool/service/impl/ParticipateFanpoolServiceImpl.java
  src/main/java/com/example/temp/user/domain/BlockedUser.java
Labels: 기능 추가, 버그 해결

#81 채팅방 목록 조회 API 응답에 팬풀 식별자 속성 추가
  src/main/java/com/example/temp/chat/domain/ChatroomRepository.java
  src/main/java/com/example/temp/chat/dto/FindChatroomListNativeDto.java
  src/main/java/com/example/temp/chat/dto/FindChatroomListResult.java
  src/main/java/com/example/temp/chat/service/impl/FindChatroomListServiceImpl.java
Labels: 기능 변경
