Repository TwoDotFive/server, pull requests merged in 2024-08, with the labels that each got.

#10 초기 채팅 기능 구현
  build.gradle
  src/main/java/com/example/temp/TempApplication.java
  src/main/java/com/example/temp/chat/config/StompHandler.java
  src/main/java/com/example/temp/chat/config/StompProperties.java
  src/main/java/com/example/temp/chat/config/WebSocketConfig.java
  src/main/java/com/example/temp/chat/controller/ChatRoomController.java
  src/main/java/com/example/temp/chat/controller/StompController.java
  src/main/java/com/example/temp/chat/domain/ChatMessage.java
  src/main/java/com/example/temp/chat/domain/ChatMessageRepository.java
  src/main/java/com/example/temp/chat/domain/ChatMessageType.java
  src/main/java/com/example/temp/chat/domain/ChatRoom.java
  src/main/java/com/example/temp/chat/domain/ChatRoomRepository.java
  src/main/java/com/example/temp/chat/domain/ChatRoomUserRepository.java
  src/main/java/com/example/temp/chat/domain/UserChatRoom.java
  src/main/java/com/example/temp/chat/domain/UserChatRoomRepository.java
  src/main/java/com/example/temp/chat/dto/ChatMessageView.java
  src/main/java/com/example/temp/chat/dto/ChatRoomView.java
  src/main/java/com/example/temp/chat/dto/ChatUserProfileView.java
  src/main/java/com/example/temp/chat/dto/CreateChatRoomCommand.java
  src/main/java/com/example/temp/chat/dto/CreateChatRoomRequest.java
  src/main/java/com/example/temp/chat/dto/CreateChatRoomResponse.java
  src/main/java/com/example/temp/chat/dto/FindChatRoomMessagesCommand.java
  src/main/java/com/example/temp/chat/dto/FindChatRoomMessagesResponse.java
  src/main/java/com/example/temp/chat/dto/FindUserJoinedChatRoomsResponse.java
  src/main/java/com/example/temp/chat/dto/LastMessageView.java
  src/main/java/com/example/temp/chat/dto/SaveChatMessageCommand.java
  src/main/java/com/example/temp/chat/dto/StompChatMessage.java
  src/main/java/com/example/temp/chat/service/CreateChatRoomService.java
  src/main/java/com/example/temp/chat/service/FindChatRoomMessagesService.java
  src/main/java/com/example/temp/chat/service/FindUserJoinedChatRoomListService.java
  src/main/java/com/example/temp/chat/service/LeaveChatRoomService.java
  src/main/java/com/example/temp/chat/service/SaveChatMessageService.java
  src/main/java/com/example/temp/chat/service/UpdateUserChatRoomExitTimeService.java
  src/main/java/com/example/temp/chat/service/impl/CreateChatRoomServiceImpl.java
  src/main/java/com/example/temp/chat/service/impl/FindChatRoomMessagesServiceImpl.java
  src/main/java/com/example/temp/chat/service/impl/FindUserJoinedChatRoomListServiceImpl.java
  src/main/java/com/example/temp/chat/service/impl/LeaveChatRoomServiceImpl.java
  src/main/java/com/example/temp/chat/service/impl/SaveChatMessageServiceImpl.java
  src/main/java/com/example/temp/chat/service/impl/UpdateUserChatRoomExitTimeServiceImpl.java
  src/main/java/com/example/temp/common/config/SecurityConfig.java
  src/main/java/com/example/temp/user/service/impl/JwtTokenService.java
Labels: Feat

#14 국문 관광 정보 조회 API 연동
  src/main/java/com/example/temp/tour/dto/FindTourInformationByLocationCommand.java
  src/main/java/com/example/temp/tour/dto/FindTourInformationByLocationHttpResponse.java
  src/main/java/com/example/temp/tour/dto/FindTourInformationResult.java
  src/main/java/com/example/temp/tour/service/FindTourInformationByLocationService.java
  src/test/java/com/example/temp/tour/dto/TourInformationBasedLocationResponseTest.java
Labels: Feat

#16 장소기반 팬풀 기능 구현
  src/main/java/com/example/temp/baseball/controller/BaseballGameController.java
  src/main/java/com/example/temp/baseball/controller/TeamController.java
  src/main/java/com/example/temp/baseball/domain/Stadium.java
  src/main/java/com/example/temp/baseball/dto/GameInformationView.java
  src/main/java/com/example/temp/baseball/dto/GameScheduleResponse.java
  src/main/java/com/example/temp/baseball/dto/TeamInformation.java
  src/main/java/com/example/temp/baseball/dto/TeamInformationView.java
  src/main/java/com/example/temp/baseball/service/FindAllTeamsInSeasonService.java
  src/main/java/com/example/temp/baseball/service/impl/FindAllTeamsInSeasonServiceImpl.java
  src/main/java/com/example/temp/fanpool/controller/FanpoolController.java
  src/main/java/com/example/temp/fanpool/domain/Fanpool.java
  src/main/java/com/example/temp/fanpool/domain/FanpoolRepository.java
  src/main/java/com/example/temp/fanpool/domain/value/FanpoolType.java
  src/main/java/com/example/temp/fanpool/domain/value/GenderConstraint.java
  src/main/java/com/example/temp/fanpool/dto/CreateFanpoolRequest.java
  src/main/java/com/example/temp/fanpool/dto/FanpoolInformationView.java
  src/main/java/com/example/temp/fanpool/dto/FindFanpoolBasedLocationCommand.java
  src/main/java/com/example/temp/fanpool/dto/FindFanpoolBasedLocationResponse.java
  src/main/java/com/example/temp/fanpool/service/FindFanpoolBasedLocationService.java
  src/main/java/com/example/temp/fanpool/service/FindFanpoolByIdService.java
  src/main/java/com/example/temp/fanpool/service/impl/CreateFanpoolServiceImpl.java
  src/main/java/com/example/temp/fanpool/service/impl/FindFanpoolBasedLocationServiceImpl.java
  src/main/java/com/example/temp/fanpool/service/impl/FindFanpoolByIdServiceImpl.java
  src/main/java/com/example/temp/geo/dto/AddressInformationView.java
  src/main/java/com/example/temp/geo/dto/FindAddressResponse.java
  src/main/java/com/example/temp/geo/dto/VworldCoord2AddressResponse.java
  src/main/java/com/example/temp/geo/entity/Address.java
  src/main/java/com/example/temp/geo/entity/AddressRepository.java
  src/main/java/com/example/temp/geo/entity/AuthenticatedLocation.java
  src/main/java/com/example/temp/geo/entity/AuthenticatedLocationRepository.java
  src/main/java/com/example/temp/geo/service/impl/Coord2AddressClient.java
  src/main/java/com/example/temp/geo/service/impl/FindAddressByCoordServiceImpl.java
  src/main/java/com/example/temp/user/controller/UserController.java
  src/main/java/com/example/temp/user/domain/UserAuthenticatedLocation.java
  src/main/java/com/example/temp/user/domain/UserAuthenticatedLocationRepository.java
  src/main/java/com/example/temp/user/dto/UserAuthenticatedLocationRequest.java
  src/main/java/com/example/temp/user/service/SaveUserAuthenticatedLocationService.java
  src/main/java/com/example/temp/user/service/impl/SaveUserAuthenticatedLocationServiceImpl.java
  src/test/java/com/example/temp/geo/dto/VworldCoord2AddressResponseTest.java
Labels: Feat

#18 경기장 목록 조회 API 구현
  src/main/java/com/example/temp/baseball/controller/StadiumController.java
  src/main/java/com/example/temp/baseball/domain/Stadium.java
  src/main/java/com/example/temp/baseball/domain/StadiumRepository.java
  src/main/java/com/example/temp/baseball/dto/FindStadiumListResponse.java
  src/main/java/com/example/temp/baseball/dto/StadiumView.java
  src/main/java/com/example/temp/baseball/dto/TeamInformationView.java
  src/main/java/com/example/temp/baseball/service/FindAllStadiumsService.java
  src/main/java/com/example/temp/baseball/service/impl/FindAllStadiumsServiceImpl.java
  src/main/java/com/example/temp/geo/dto/AddressInformationView.java
Labels: Feat, Refactor

#19 위치 기반 관광 정보 조회 API 구현
  src/main/java/com/example/temp/tour/controller/TourController.java
  src/main/java/com/example/temp/tour/dto/FindTourInformationByLocationCommand.java
  src/main/java/com/example/temp/tour/dto/FindTourInformationByLocationHttpResponse.java
  src/main/java/com/example/temp/tour/dto/FindTourInformationResponse.java
  src/main/java/com/example/temp/tour/dto/FindTourInformationResult.java
  src/main/java/com/example/temp/tour/dto/TourInformation.java
  src/main/java/com/example/temp/tour/dto/TourInformationSummary.java
  src/main/java/com/example/temp/tour/service/FindTourInformationByLocationService.java
  src/main/java/com/example/temp/tour/service/impl/FindTourInformationByLocationServiceImpl.java
Labels: Feat

#22 JPA Auditing 미동작 오류 해결
  src/main/java/com/example/temp/common/config/JpaConfig.java
Labels: Fix

#23 CORS 오류 해결
  src/main/java/com/example/temp/common/config/SecurityConfig.java
Labels: Fix
